version: '2'

volumes:
    orderer.testnet.com:
    peer0.orga.testnet.com:
    cli.testnet.com:

networks:
  testnet:

services:
    orderer.testnet.com:
        container_name: orderer.testnet.com
        image: hyperledger/fabric-orderer:1.4.0
        environment:
            # - FABRIC_LOGGING_SPEC=INFO
            - FABRIC_LOGGING_SPEC=DEBUG
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=Orderer
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            # enabled TLS
            - ORDERER_GENERAL_TLS_ENABLED=false
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
            - ORDERER_KAFKA_VERBOSE=true
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
            - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./crypto-config/ordererOrganizations/testnet.com/orderers/orderer.testnet.com/msp:/var/hyperledger/orderer/msp
            - ./crypto-config/ordererOrganizations/testnet.com/orderers/orderer.testnet.com/tls:/var/hyperledger/orderer/tls
            - orderer.testnet.com:/var/hyperledger/production/orderer
        networks:
            - testnet

    couchdb.orga.testnet.com:
        container_name: couchdb.orga.testnet.com
        image: hyperledger/fabric-couchdb:0.4.14
        environment:
            - COUCHDB_USER=
            - COUCHDB_PASSWORD=
        # ports:
            # - "5984:5984"
        networks:
            - testnet 

    peer0.orga.testnet.com:
        container_name: peer0.orga.testnet.com
        image: hyperledger/fabric-peer:1.4.0
        environment:
            # peer env
            - CORE_PEER_ID=peer0.orga.testnet.com
            - CORE_PEER_ADDRESS=${DOCKER_COMPOSE_PEER_ADDRESS}
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=${DOCKER_COMPOSE_PEER_CC_ADDRESS}
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=${DOCKER_COMPOSE_PEER_GOSSIP_BOOTSTRAP}
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${DOCKER_COMPOSE_PEER_ADDRESS}
            - CORE_PEER_LOCALMSPID=OrgA
            # state database
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.orga.testnet.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
            # basic env
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_testnet
              # - FABRIC_LOGGING_SPEC=INFO
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/orga.testnet.com/peers/peer0.orga.testnet.com/msp:/etc/hyperledger/fabric/msp
            - ./crypto-config/peerOrganizations/orga.testnet.com/peers/peer0.orga.testnet.com/tls:/etc/hyperledger/fabric/tls
            - peer0.orga.testnet.com:/var/hyperledger/production
        networks:
            - testnet

    cli.testnet.com:
        container_name: cli.testnet.com
        image: hyperledger/fabric-tools:1.4.0
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
              # - FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=${CORE_PEER_ADDRESS}
            - CORE_PEER_LOCALMSPID=OrgA
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.testnet.com/peers/peer0.orga.testnet.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.testnet.com/peers/peer0.orga.testnet.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.testnet.com/peers/peer0.orga.testnet.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.testnet.com/users/Admin@orga.testnet.com/msp
            - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/testnet.com/orderers/orderer.testnet.com/tls/ca.crt
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        depends_on:
            - orderer.testnet.com
            - peer0.orga.testnet.com
        volumes:
            - /var/run/:/host/var/run/
            - ./chaincode/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        networks:
            - testnet
